Feat/manage song
sing-4u/web pull request #48
Opened 2024-11-18 12:45 UTC by GILPYO

### 새로운 기능
 - [ ] 버그 수정
 - [ ] 코드 스타일 업데이트 (포맷팅, 변수명 변경 등)
 - [ ] 리팩토링 (기능 변경 없는 코드 개선)
 - [ ] 문서 내용 변경
 - [ ] 기타 (설명해주세요):

### 테스트 계획
모바일에서 Pull to refresh 테스트 예정

2024-11-18 18:37 UTC, HA-SEUNG-JEONG commented on src/pages/Mypage.tsx
>      refetch();
이건 그냥 궁금한건데 로그아웃 시에 refetch를 하신 이유가 있을까요?

2024-11-18 18:37 UTC, HA-SEUNG-JEONG commented
충돌 확인 부탁드립니다! @GILPYO

2024-11-19 05:54 UTC, HA-SEUNG-JEONG requested changes
충돌 확인 부탁드립니다!

2024-11-19 08:42 UTC, GILPYO commented on src/pages/Mypage.tsx
>      refetch();
로그아웃 후에 사용자 데이터가 캐시에 남아있을 가능성 때문에 써봤는데  로그아웃 후 바로 리다이렉트로 수정하면서 삭제했어야 할 코드네요 이것저것 테스트해보다가 깜빡하고 삭제 안 했네요ㅠ

2024-11-19 08:49 UTC, merged